<script>
	import { onMount } from 'svelte';
	export let tool;

	let messages = [];
	let currentMessage = '';
	let isLoading = false;
	let chatContainer;

	// Mock AI response for now
	async function sendMessage() {
		if (!currentMessage.trim() || isLoading) return;

		// Add user message
		const userMessage = {
			id: Date.now(),
			content: currentMessage,
			role: 'user',
			timestamp: new Date()
		};
		messages = [...messages, userMessage];
		
		const messageToSend = currentMessage;
		currentMessage = '';
		isLoading = true;

		// Scroll to bottom
		setTimeout(() => {
			if (chatContainer) {
				chatContainer.scrollTop = chatContainer.scrollHeight;
			}
		}, 100);

		// Mock AI response (replace with actual API call later)
		setTimeout(() => {
			const aiMessage = {
				id: Date.now() + 1,
				content: `This is a mock response from the ${tool.name}. In a real implementation, this would be generated by ${tool.model} using the system prompt: "${tool.systemPrompt.substring(0, 100)}..."`,
				role: 'assistant',
				timestamp: new Date()
			};
			messages = [...messages, aiMessage];
			isLoading = false;

			// Scroll to bottom
			setTimeout(() => {
				if (chatContainer) {
					chatContainer.scrollTop = chatContainer.scrollHeight;
				}
			}, 100);
		}, 1000);
	}

	function handleKeydown(event) {
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			sendMessage();
		}
	}

	onMount(() => {
		// Add welcome message
		messages = [{
			id: 0,
			content: `Hello! I'm your ${tool.name}. ${tool.description} How can I help you today?`,
			role: 'assistant',
			timestamp: new Date()
		}];
	});
</script>

<div class="flex flex-col h-full">
	<!-- Chat Header -->
	<div class="bg-white border-b px-6 py-4 flex items-center space-x-3">
		<span class="text-2xl">{tool.icon}</span>
		<div>
			<h2 class="text-lg font-semibold text-gray-900">{tool.name}</h2>
			<p class="text-sm text-gray-500">{tool.description}</p>
		</div>
	</div>

	<!-- Messages Container -->
	<div 
		bind:this={chatContainer}
		class="flex-1 overflow-y-auto p-6 space-y-4 bg-gray-50"
	>
		{#each messages as message}
			<div class="flex {message.role === 'user' ? 'justify-end' : 'justify-start'}">
				<div class="max-w-xs lg:max-w-md px-4 py-2 rounded-lg {
					message.role === 'user' 
						? 'bg-primary-500 text-white' 
						: 'bg-white text-gray-900 shadow-sm border'
				}">
					<p class="text-sm">{message.content}</p>
					<p class="text-xs mt-1 {message.role === 'user' ? 'text-primary-100' : 'text-gray-500'}">
						{message.timestamp.toLocaleTimeString()}
					</p>
				</div>
			</div>
		{/each}

		{#if isLoading}
			<div class="flex justify-start">
				<div class="bg-white text-gray-900 shadow-sm border rounded-lg px-4 py-2">
					<div class="flex space-x-1">
						<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
						<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay: 0.1s"></div>
						<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay: 0.2s"></div>
					</div>
				</div>
			</div>
		{/if}
	</div>

	<!-- Input Area -->
	<div class="bg-white border-t p-4">
		<div class="flex space-x-3">
			<textarea
				bind:value={currentMessage}
				on:keydown={handleKeydown}
				placeholder="Type your message here..."
				class="flex-1 resize-none border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
				rows="1"
				disabled={isLoading}
			></textarea>
			<button
				on:click={sendMessage}
				disabled={!currentMessage.trim() || isLoading}
				class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
			>
				Send
			</button>
		</div>
		<div class="mt-2 flex items-center justify-between text-xs text-gray-500">
			<span>Press Enter to send, Shift+Enter for new line</span>
			<span>Model: {tool.model}</span>
		</div>
	</div>
</div> 